---
 - name: Add script to fix kernel bug
   become: no
   copy:
      src: '{{ item }}'
      dest: '~/.local/bin/{{ item }}'
      mode: 0740
   with_items:
    - mmc-bug-fix

 - name: Install packages for exFAT
   become: yes
   apt:
     name: '{{ item }}'
     state: present
     update_cache: yes
     cache_valid_time: 3600
   with_items:
    - exfat-fuse
    - exfat-utils
