---
 - name: Install git package
   sudo: true
   apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
   with_items:
    - git

 - name: Git initial setup
   template: src=.{{ item }}.j2 dest=~/.{{ item }}
   with_items:
    - gitconfig
    - gitexcludes

 - name: Add git extension commands
   copy: src={{ item }} dest=~/.local/bin/{{ item }}
      mode=0740
   with_items:
    - git-extract