---
 - name: Ensure existence of Downloads directory
   file:
     path: ~/Downloads
     state: directory

# TODO: Detect lastest version of QtCreator
 - name: Download QtCreator
   get_url:
     url: 'http://download.qt.io/official_releases/qtcreator/3.6/3.6.0/qt-creator-opensource-linux-x86_64-3.6.0.run'
     dest: ~/Downloads/qt-creator-installer.run

 - name: Change mode of downloaded file
   file:
     path: ~/Downloads/qt-creator-installer.run
     mode: a+x

 - name: Run QtCreator Installer
   shell: ~/Downloads/qt-creator-installer.run
