---
 - name: Install common packages
   apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
   with_items:
    - htop
    - psmisc
    - mc
    - wget
    - curl
    - vim
    - iftop
    - tcpdump
    - gdebi
    - software-properties-common
    - tree
