---
 - name: Add docker group
   become: yes
   group:
     name: docker
     state: present

 - name: Add user to docker group
   become: yes
   user:
     name: '{{ ansible_user_id }}'
     groups: docker
     state: present
     append: yes

 - name: Create directory for docker graph
   become: yes
   file:
     path: /home/docker
     state: directory
     owner: root
     group: docker
     mode: 0701

 - name: Install docker requirements
   become: yes
   apt:
     name: '{{ item }}'
     state: present
     update_cache: yes
     cache_valid_time: 3600
   with_items:
    - curl

 - name: Download docker installer
   become: yes
   shell: curl -fsSL -o /tmp/docker-installer.sh https://get.docker.com/
   args:
      creates: /tmp/docker-installer.sh
# TODO: use get_url instead of curl after fixing https://github.com/ansible/ansible/issues/12161
#   get_url:
#      url: 'https://get.docker.com/'
#      dest: /tmp/docker-installer.sh
#      mode: a+rwx
   # TODO: add docker plugin to oh-my-zsh

 - name: Run docker installer
   become: yes
   script: /tmp/docker-installer.sh

 - name: Set up docker
   become: yes
   template:
     src: docker.j2
     dest: /etc/default/docker
     owner: root
     group: root
     mode: 0644
   notify: Restart docker service

 - name: Create local bin directory
   become: no
   file:
     path: ~/.local/bin/
     state : directory
     mode: 0750

 - name: Download docker compose
   become: no
   get_url:
     url: 'https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}'
     dest: ~/.local/bin/docker-compose
     mode: 0750
   # TODO: add docker-compose to oh-my-zsh
