---
 - name: Install common developer packages
   apt: name={{item}} state=present update_cache=no
   with_items:
    - build-essential
    - automake
    - autoconf
    - psmisc
    - git
    - git-gui
    - gitk
    - gitg
    - valgrind
    - wireshark

