---
 - name: Install common developer packages
   apt:
     name: '{{item}}'
     state: present
     update_cache: yes
     cache_valid_time: 3600
   with_items:
    - build-essential
    - automake
    - autoconf
    - psmisc
    - git
    - git-gui
    - gitk
    - gitg
    - valgrind
    - wireshark

